// Unified Autocomplete Tickers Database - Generated Automatically
export const ALL_ASSETS = [
  { ticker: '005930', name: '삼성전자 (Samsung Elec)', sector: 'Technology', basePrice: 72000 },
  { ticker: '000660', name: 'SK하이닉스 (SK Hynix)', sector: 'Technology', basePrice: 165000 },
  { ticker: '005380', name: '현대자동차 (Hyundai Motor)', sector: 'Consumer', basePrice: 245000 },
  { ticker: '035420', name: 'NAVER (네이버)', sector: 'Communication', basePrice: 195000 },
  { ticker: '035720', name: '카카오 (Kakao)', sector: 'Communication', basePrice: 48000 },
  { ticker: '068270', name: '셀트리온 (Celltrion)', sector: 'Healthcare', basePrice: 180000 },
  { ticker: '051910', name: 'LG화학 (LG Chem)', sector: 'Materials', basePrice: 420000 },
  { ticker: '000270', name: '기아 (Kia)', sector: 'Consumer', basePrice: 115000 },
  { ticker: '005490', name: 'POSCO홀딩스 (POSCO)', sector: 'Materials', basePrice: 380000 },
  { ticker: '035900', name: 'JYP엔터테인먼트 (JYP Ent.)', sector: 'Communication', basePrice: 65000 },
  { ticker: 'AAPL', name: 'Apple Inc.', sector: 'Technology', basePrice: 195.5 },
  { ticker: 'MSFT', name: 'Microsoft Corp.', sector: 'Technology', basePrice: 420.2 },
  { ticker: 'NVDA', name: 'NVIDIA Corp.', sector: 'Technology', basePrice: 910.5 },
  { ticker: 'GOOGL', name: 'Alphabet Inc.', sector: 'Technology', basePrice: 172.4 },
  { ticker: 'AMZN', name: 'Amazon.com, Inc.', sector: 'Consumer', basePrice: 185.1 },
  { ticker: 'META', name: 'Meta Platforms, Inc.', sector: 'Communication', basePrice: 480.8 },
  { ticker: 'TSLA', name: 'Tesla, Inc.', sector: 'Consumer', basePrice: 175.5 },
  { ticker: 'BRK.B', name: 'Berkshire Hathaway Inc.', sector: 'Finance', basePrice: 410.3 },
  { ticker: 'LLY', name: 'Eli Lilly and Company', sector: 'Healthcare', basePrice: 780.0 },
  { ticker: 'AVGO', name: 'Broadcom Inc.', sector: 'Technology', basePrice: 1350.0 },
  { ticker: 'JPM', name: 'JPMorgan Chase & Co.', sector: 'Finance', basePrice: 195.2 },
  { ticker: 'V', name: 'Visa Inc.', sector: 'Finance', basePrice: 275.4 },
  { ticker: 'UNH', name: 'UnitedHealth Group Inc.', sector: 'Healthcare', basePrice: 490.5 },
  { ticker: 'WMT', name: 'Walmart Inc.', sector: 'Consumer', basePrice: 65.2 },
  { ticker: 'MA', name: 'Mastercard Incorporated', sector: 'Finance', basePrice: 450.1 },
  { ticker: 'PG', name: 'Procter & Gamble Co.', sector: 'Consumer', basePrice: 165.3 },
  { ticker: 'XOM', name: 'Exxon Mobil Corp.', sector: 'Energy', basePrice: 118.4 },
  { ticker: 'JNJ', name: 'Johnson & Johnson', sector: 'Healthcare', basePrice: 155.8 },
  { ticker: 'HD', name: 'Home Depot, Inc.', sector: 'Consumer', basePrice: 345.5 },
  { ticker: 'MRK', name: 'Merck & Co., Inc.', sector: 'Healthcare', basePrice: 125.2 },
  { ticker: 'COST', name: 'Costco Wholesale Corp.', sector: 'Consumer', basePrice: 725.6 },
  { ticker: 'ABBV', name: 'AbbVie Inc.', sector: 'Healthcare', basePrice: 168.9 },
  { ticker: 'CVX', name: 'Chevron Corp.', sector: 'Energy', basePrice: 155.2 },
  { ticker: 'AMD', name: 'Advanced Micro Devices', sector: 'Technology', basePrice: 160.4 },
  { ticker: 'CRM', name: 'Salesforce, Inc.', sector: 'Technology', basePrice: 280.1 },
  { ticker: 'NFLX', name: 'Netflix, Inc.', sector: 'Communication', basePrice: 610.5 },
  { ticker: 'PEP', name: 'PepsiCo, Inc.', sector: 'Consumer', basePrice: 172.3 },
  { ticker: 'KO', name: 'Coca-Cola Co.', sector: 'Consumer', basePrice: 62.5 },
  { ticker: 'ADBE', name: 'Adobe Inc.', sector: 'Technology', basePrice: 490.2 },
  { ticker: 'DIS', name: 'Walt Disney Co.', sector: 'Communication', basePrice: 112.4 },
  { ticker: 'BAC', name: 'Bank of America Corp.', sector: 'Finance', basePrice: 38.2 },
  { ticker: 'ACN', name: 'Accenture plc', sector: 'Technology', basePrice: 330.5 },
  { ticker: 'CSCO', name: 'Cisco Systems, Inc.', sector: 'Technology', basePrice: 48.9 },
  { ticker: 'QCOM', name: 'Qualcomm Inc.', sector: 'Technology', basePrice: 175.4 },
  { ticker: 'TMO', name: 'Thermo Fisher Scientific', sector: 'Healthcare', basePrice: 560.1 },
  { ticker: 'INTC', name: 'Intel Corp.', sector: 'Technology', basePrice: 30.5 },
  { ticker: 'ABT', name: 'Abbott Laboratories', sector: 'Healthcare', basePrice: 110.2 },
  { ticker: 'CAT', name: 'Caterpillar Inc.', sector: 'Industrial', basePrice: 350.6 },
  { ticker: 'TXN', name: 'Texas Instruments Inc.', sector: 'Technology', basePrice: 170.8 },
  { ticker: 'VZ', name: 'Verizon Communications', sector: 'Communication', basePrice: 40.2 },
  { ticker: 'CMCSA', name: 'Comcast Corp.', sector: 'Communication', basePrice: 42.1 },
  { ticker: 'AMGN', name: 'Amgen Inc.', sector: 'Healthcare', basePrice: 280.5 },
  { ticker: 'IBM', name: 'International Business Machines', sector: 'Technology', basePrice: 170.4 },
  { ticker: 'COP', name: 'ConocoPhillips', sector: 'Energy', basePrice: 120.2 },
  { ticker: 'PM', name: 'Philip Morris International', sector: 'Consumer', basePrice: 100.5 },
  { ticker: 'AXP', name: 'American Express Co.', sector: 'Finance', basePrice: 225.1 },
  { ticker: 'UNP', name: 'Union Pacific Corp.', sector: 'Industrial', basePrice: 235.4 },
  { ticker: 'GS', name: 'Goldman Sachs Group', sector: 'Finance', basePrice: 410.8 },
  { ticker: 'SPGI', name: 'S&P Global Inc.', sector: 'Finance', basePrice: 430.5 },
  { ticker: 'HON', name: 'Honeywell International', sector: 'Industrial', basePrice: 198.4 },
  { ticker: 'RTX', name: 'RTX Corporation', sector: 'Industrial', basePrice: 98.2 },
  { ticker: 'PLTR', name: 'Palantir Technologies Inc.', sector: 'Technology', basePrice: 22.5 },
  { ticker: 'SBUX', name: 'Starbucks Corp.', sector: 'Consumer', basePrice: 85.4 },
  { ticker: 'GE', name: 'General Electric Co.', sector: 'Industrial', basePrice: 155.8 },
  { ticker: 'NOW', name: 'ServiceNow, Inc.', sector: 'Technology', basePrice: 740.5 },
  { ticker: 'ISRG', name: 'Intuitive Surgical, Inc.', sector: 'Healthcare', basePrice: 385.2 },
  { ticker: 'LRCX', name: 'Lam Research Corp.', sector: 'Technology', basePrice: 940.1 },
  { ticker: 'SYK', name: 'Stryker Corp.', sector: 'Healthcare', basePrice: 345.4 },
  { ticker: 'MDLZ', name: 'Mondelez International', sector: 'Consumer', basePrice: 72.4 },
  { ticker: 'REGN', name: 'Regeneron Pharmaceuticals', sector: 'Healthcare', basePrice: 920.8 },
  { ticker: 'VRTX', name: 'Vertex Pharmaceuticals', sector: 'Healthcare', basePrice: 420.5 },
  { ticker: 'PFE', name: 'Pfizer Inc.', sector: 'Healthcare', basePrice: 28.4 },
  { ticker: 'BA', name: 'Boeing Co.', sector: 'Industrial', basePrice: 180.2 },
  { ticker: 'DE', name: 'Deere & Company', sector: 'Industrial', basePrice: 380.5 },
  { ticker: 'MMM', name: '3M Company', sector: 'Industrial', basePrice: 98.1 },
  { ticker: 'ORCL', name: 'Oracle Corp.', sector: 'Technology', basePrice: 115.4 },
  { ticker: 'PYPL', name: 'PayPal Holdings, Inc.', sector: 'Finance', basePrice: 62.4 },
  { ticker: 'SQ', name: 'Block, Inc.', sector: 'Finance', basePrice: 70.5 },
  { ticker: 'SHOP', name: 'Shopify Inc.', sector: 'Consumer', basePrice: 75.2 },
  { ticker: 'UBER', name: 'Uber Technologies, Inc.', sector: 'Consumer', basePrice: 70.8 },
  { ticker: 'ABNB', name: 'Airbnb, Inc.', sector: 'Consumer', basePrice: 155.4 },
  { ticker: 'COIN', name: 'Coinbase Global, Inc.', sector: 'Finance', basePrice: 220.5 },
  { ticker: 'F', name: 'Ford Motor Co.', sector: 'Consumer', basePrice: 12.1 },
  { ticker: 'GM', name: 'General Motors Co.', sector: 'Consumer', basePrice: 42.5 },
  { ticker: 'T', name: 'AT&T Inc.', sector: 'Communication', basePrice: 16.8 },
  { ticker: 'TMUS', name: 'T-Mobile US, Inc.', sector: 'Communication', basePrice: 160.2 },
  { ticker: 'MRNA', name: 'Moderna, Inc.', sector: 'Healthcare', basePrice: 110.5 },
  { ticker: 'SLB', name: 'Schlumberger N.V.', sector: 'Energy', basePrice: 48.5 },
  { ticker: 'OXY', name: 'Occidental Petroleum', sector: 'Energy', basePrice: 62.4 },
  { ticker: 'BX', name: 'Blackstone Inc.', sector: 'Finance', basePrice: 120.4 },
  { ticker: 'KKR', name: 'KKR & Co. Inc.', sector: 'Finance', basePrice: 95.2 },
  { ticker: 'MS', name: 'Morgan Stanley', sector: 'Finance', basePrice: 90.8 },
  { ticker: 'C', name: 'Citigroup Inc.', sector: 'Finance', basePrice: 58.4 },
  { ticker: 'WFC', name: 'Wells Fargo & Co.', sector: 'Finance', basePrice: 56.5 },
  { ticker: 'AMT', name: 'American Tower Corp.', sector: 'Real Estate', basePrice: 195.4 },
  { ticker: 'PLD', name: 'Prologis, Inc.', sector: 'Real Estate', basePrice: 115.2 },
  { ticker: 'EQIX', name: 'Equinix, Inc.', sector: 'Real Estate', basePrice: 810.5 },
  { ticker: 'SPG', name: 'Simon Property Group', sector: 'Real Estate', basePrice: 145.2 },
  { ticker: 'O', name: 'Realty Income Corp.', sector: 'Real Estate', basePrice: 54.3 },
  { ticker: 'DLR', name: 'Digital Realty Trust', sector: 'Real Estate', basePrice: 142.1 },
  { ticker: 'NEE', name: 'NextEra Energy, Inc.', sector: 'Utilities', basePrice: 62.5 },
  { ticker: 'DUK', name: 'Duke Energy Corp.', sector: 'Utilities', basePrice: 96.4 },
  { ticker: 'SO', name: 'Southern Company', sector: 'Utilities', basePrice: 70.2 },
  { ticker: 'SHW', name: 'Sherwin-Williams Co.', sector: 'Materials', basePrice: 320.5 },
  { ticker: 'FCX', name: 'Freeport-McMoRan Inc.', sector: 'Materials', basePrice: 48.2 },
  { ticker: 'ECL', name: 'Ecolab Inc.', sector: 'Materials', basePrice: 220.4 },
  { ticker: 'APD', name: 'Air Products & Chemicals', sector: 'Materials', basePrice: 240.2 },
  { ticker: 'NEM', name: 'Newmont Corporation', sector: 'Materials', basePrice: 38.5 },
  { ticker: 'PANW', name: 'Palo Alto Networks', sector: 'Technology', basePrice: 285.5 },
  { ticker: 'SNOW', name: 'Snowflake Inc.', sector: 'Technology', basePrice: 158.4 },
  { ticker: 'CRWD', name: 'CrowdStrike Holdings', sector: 'Technology', basePrice: 310.2 },
  { ticker: 'NET', name: 'Cloudflare, Inc.', sector: 'Technology', basePrice: 92.4 },
  { ticker: 'DDOG', name: 'Datadog, Inc.', sector: 'Technology', basePrice: 122.5 },
  { ticker: 'MDB', name: 'MongoDB, Inc.', sector: 'Technology', basePrice: 360.5 },
  { ticker: 'TTD', name: 'The Trade Desk', sector: 'Technology', basePrice: 85.4 },
  { ticker: 'TEAM', name: 'Atlassian Corp.', sector: 'Technology', basePrice: 195.2 },
  { ticker: 'WDAY', name: 'Workday, Inc.', sector: 'Technology', basePrice: 260.5 },
  { ticker: 'HUBS', name: 'HubSpot, Inc.', sector: 'Technology', basePrice: 620.4 },
  { ticker: 'OKTA', name: 'Okta, Inc.', sector: 'Technology', basePrice: 95.5 },
  { ticker: 'TWLO', name: 'Twilio Inc.', sector: 'Technology', basePrice: 60.2 },
  { ticker: 'ZM', name: 'Zoom Video Communications', sector: 'Technology', basePrice: 65.4 },
  { ticker: 'BILL', name: 'Bill.com Holdings', sector: 'Technology', basePrice: 70.2 },
  { ticker: 'PATH', name: 'UiPath Inc.', sector: 'Technology', basePrice: 19.5 },
  { ticker: 'MNDY', name: 'monday.com Ltd.', sector: 'Technology', basePrice: 220.4 },
  { ticker: 'DOCU', name: 'DocuSign, Inc.', sector: 'Technology', basePrice: 58.2 },
  { ticker: 'RBLX', name: 'Roblox Corp.', sector: 'Technology', basePrice: 38.5 },
  { ticker: 'U', name: 'Unity Software Inc.', sector: 'Technology', basePrice: 26.4 },
  { ticker: 'ROKU', name: 'Roku, Inc.', sector: 'Technology', basePrice: 62.5 },
  { ticker: 'ZS', name: 'Zscaler, Inc.', sector: 'Technology', basePrice: 195.4 },
  { ticker: 'APO', name: 'Apollo Global Management', sector: 'Finance', basePrice: 112.5 },
  { ticker: 'SCHW', name: 'Charles Schwab Corp.', sector: 'Finance', basePrice: 72.4 },
  { ticker: 'BLK', name: 'BlackRock, Inc.', sector: 'Finance', basePrice: 780.4 },
  { ticker: 'PNC', name: 'PNC Financial Services', sector: 'Finance', basePrice: 152.4 },
  { ticker: 'USB', name: 'U.S. Bancorp', sector: 'Finance', basePrice: 41.2 },
  { ticker: 'AIG', name: 'American International Group', sector: 'Finance', basePrice: 75.6 },
  { ticker: 'MET', name: 'MetLife, Inc.', sector: 'Finance', basePrice: 70.4 },
  { ticker: 'PRU', name: 'Prudential Financial', sector: 'Finance', basePrice: 112.5 },
  { ticker: 'TRV', name: 'Travelers Companies', sector: 'Finance', basePrice: 220.2 },
  { ticker: 'CB', name: 'Chubb Limited', sector: 'Finance', basePrice: 250.4 },
  { ticker: 'ALL', name: 'Allstate Corp.', sector: 'Finance', basePrice: 165.2 },
  { ticker: 'AFL', name: 'Aflac Inc.', sector: 'Finance', basePrice: 82.4 },
  { ticker: 'GILD', name: 'Gilead Sciences, Inc.', sector: 'Healthcare', basePrice: 72.5 },
  { ticker: 'MDT', name: 'Medtronic plc', sector: 'Healthcare', basePrice: 84.6 },
  { ticker: 'VEEV', name: 'Veeva Systems Inc.', sector: 'Healthcare', basePrice: 210.4 },
  { ticker: 'KLAC', name: 'KLA Corporation', sector: 'Technology', basePrice: 680.5 },
  { ticker: 'MRVL', name: 'Marvell Technology', sector: 'Technology', basePrice: 70.5 },
  { ticker: 'FTNT', name: 'Fortinet, Inc.', sector: 'Technology', basePrice: 65.2 },
  { ticker: 'LYFT', name: 'Lyft, Inc.', sector: 'Consumer', basePrice: 15.4 },
  { ticker: 'NIO', name: 'NIO Inc.', sector: 'Consumer', basePrice: 5.2 },
  { ticker: 'RIVN', name: 'Rivian Automotive', sector: 'Consumer', basePrice: 11.4 },
  { ticker: 'LCID', name: 'Lucid Group, Inc.', sector: 'Consumer', basePrice: 3.1 },
  { ticker: 'RCL', name: 'Royal Caribbean Cruises', sector: 'Consumer', basePrice: 135.2 },
  { ticker: 'CCL', name: 'Carnival Corp.', sector: 'Consumer', basePrice: 16.4 },
  { ticker: 'MAR', name: 'Marriott International', sector: 'Consumer', basePrice: 245.5 },
  { ticker: 'HLT', name: 'Hilton Worldwide Holdings', sector: 'Consumer', basePrice: 200.2 },
  { ticker: 'H', name: 'Hyatt Hotels Corp.', sector: 'Consumer', basePrice: 145.4 },
  { ticker: 'DAL', name: 'Delta Air Lines, Inc.', sector: 'Consumer', basePrice: 46.2 },
  { ticker: 'UAL', name: 'United Airlines Holdings', sector: 'Consumer', basePrice: 48.5 },
  { ticker: 'LUV', name: 'Southwest Airlines Co.', sector: 'Consumer', basePrice: 28.4 },
  { ticker: 'YUM', name: 'Yum! Brands, Inc.', sector: 'Consumer', basePrice: 138.2 },
  { ticker: 'CMG', name: 'Chipotle Mexican Grill', sector: 'Consumer', basePrice: 2880.0 },
  { ticker: 'DVN', name: 'Devon Energy Corp.', sector: 'Energy', basePrice: 50.4 },
  { ticker: 'MPC', name: 'Marathon Petroleum', sector: 'Energy', basePrice: 195.2 },
  { ticker: 'PSX', name: 'Phillips 66', sector: 'Energy', basePrice: 158.4 },
  { ticker: 'VLO', name: 'Valero Energy Corp.', sector: 'Energy', basePrice: 165.5 },
  { ticker: 'HAL', name: 'Halliburton Co.', sector: 'Energy', basePrice: 38.2 },
  { ticker: 'BKR', name: 'Baker Hughes Co.', sector: 'Energy', basePrice: 32.5 },
  { ticker: 'LMT', name: 'Lockheed Martin Corp.', sector: 'Industrial', basePrice: 450.4 },
  { ticker: 'GD', name: 'General Dynamics', sector: 'Industrial', basePrice: 285.2 },
  { ticker: 'NOC', name: 'Northrop Grumman Corp.', sector: 'Industrial', basePrice: 460.1 },
  { ticker: 'GEV', name: 'GE Vernova Inc.', sector: 'Utilities', basePrice: 135.2 },
  { ticker: 'WM', name: 'Waste Management, Inc.', sector: 'Industrial', basePrice: 205.4 },
  { ticker: 'RSG', name: 'Republic Services, Inc.', sector: 'Industrial', basePrice: 188.5 },
  { ticker: 'FDX', name: 'FedEx Corp.', sector: 'Industrial', basePrice: 255.4 },
  { ticker: 'UPS', name: 'United Parcel Service', sector: 'Industrial', basePrice: 145.2 },
  { ticker: 'AAL', name: 'American Airlines Group', sector: 'Consumer', basePrice: 12.8 },
  { ticker: 'ALK', name: 'Alaska Air Group', sector: 'Consumer', basePrice: 38.5 },
  { ticker: 'LUV2', name: 'Southwest Airlines B', sector: 'Consumer', basePrice: 27.5 },
  { ticker: 'JBLU', name: 'JetBlue Airways', sector: 'Consumer', basePrice: 5.8 },
  { ticker: 'SAVE', name: 'Spirit Airlines', sector: 'Consumer', basePrice: 4.5 },
  { ticker: 'HA', name: 'Hawaiian Holdings', sector: 'Consumer', basePrice: 11.2 },
  { ticker: 'ALGT', name: 'Allegiant Travel Co.', sector: 'Consumer', basePrice: 68.4 },
  { ticker: 'SKYW', name: 'SkyWest, Inc.', sector: 'Consumer', basePrice: 62.5 },
  { ticker: 'RYAAY', name: 'Ryanair Holdings', sector: 'Consumer', basePrice: 122.5 },
  { ticker: 'LFL', name: 'LATAM Airlines Group', sector: 'Consumer', basePrice: 22.4 },
  { ticker: 'CPA', name: 'Copa Holdings, S.A.', sector: 'Consumer', basePrice: 92.5 },
  { ticker: 'CEA', name: 'China Eastern Airlines', sector: 'Consumer', basePrice: 16.4 },
  { ticker: 'ZNH', name: 'China Southern Airlines', sector: 'Consumer', basePrice: 24.5 },
  { ticker: 'AFRAF', name: 'Air France-KLM', sector: 'Consumer', basePrice: 9.8 },
  { ticker: 'DLAKY', name: 'Deutsche Lufthansa', sector: 'Consumer', basePrice: 7.2 },
  { ticker: 'SNCY', name: 'Sun Country Airlines', sector: 'Consumer', basePrice: 14.5 },
  { ticker: 'UP', name: 'Wheels Up Experience', sector: 'Consumer', basePrice: 2.1 },
  { ticker: 'MSTR', name: 'MicroStrategy Inc.', sector: 'Technology', basePrice: 1450.0 },
  { ticker: 'RIOT', name: 'Riot Platforms, Inc.', sector: 'Technology', basePrice: 10.2 },
  { ticker: 'MARA', name: 'Marathon Digital', sector: 'Technology', basePrice: 18.5 },
  { ticker: 'HUT', name: 'Hut 8 Corp.', sector: 'Technology', basePrice: 9.5 },
  { ticker: 'CLSK', name: 'CleanSpark, Inc.', sector: 'Technology', basePrice: 14.2 },
  { ticker: 'BTC', name: 'Bitcoin', sector: 'Crypto', basePrice: 67200.0 },
  { ticker: 'ETH', name: 'Ethereum', sector: 'Crypto', basePrice: 3450.0 },
  { ticker: 'BNB', name: 'BNB', sector: 'Crypto', basePrice: 580.0 },
  { ticker: 'SOL', name: 'Solana', sector: 'Crypto', basePrice: 142.5 },
  { ticker: 'XRP', name: 'XRP', sector: 'Crypto', basePrice: 0.48 },
  { ticker: 'ADA', name: 'Cardano', sector: 'Crypto', basePrice: 0.38 },
  { ticker: 'DOGE', name: 'Dogecoin', sector: 'Crypto', basePrice: 0.12 },
  { ticker: 'DOT', name: 'Polkadot', sector: 'Crypto', basePrice: 5.8 },
  { ticker: 'AVAX', name: 'Avalanche', sector: 'Crypto', basePrice: 28.5 },
  { ticker: 'LINK', name: 'Chainlink', sector: 'Crypto', basePrice: 13.8 },
  { ticker: 'MATIC', name: 'Polygon', sector: 'Crypto', basePrice: 0.58 },
  { ticker: 'UNI', name: 'Uniswap', sector: 'Crypto', basePrice: 7.2 },
  { ticker: 'ATOM', name: 'Cosmos', sector: 'Crypto', basePrice: 6.5 },
  { ticker: 'LTC', name: 'Litecoin', sector: 'Crypto', basePrice: 72.4 },
  { ticker: 'NEAR', name: 'NEAR Protocol', sector: 'Crypto', basePrice: 4.8 },
  { ticker: 'APT', name: 'Aptos', sector: 'Crypto', basePrice: 6.2 },
  { ticker: 'ARB', name: 'Arbitrum', sector: 'Crypto', basePrice: 0.82 },
  { ticker: 'OP', name: 'Optimism', sector: 'Crypto', basePrice: 1.85 },
  { ticker: 'ICP', name: 'Internet Computer', sector: 'Crypto', basePrice: 8.2 },
  { ticker: 'STX', name: 'Stacks', sector: 'Crypto', basePrice: 1.65 },
  { ticker: 'IMX', name: 'Immutable', sector: 'Crypto', basePrice: 1.25 },
  { ticker: 'AAVE', name: 'Aave', sector: 'Crypto', basePrice: 88.5 },
  { ticker: 'MKR', name: 'Maker', sector: 'Crypto', basePrice: 2200.0 },
  { ticker: 'RENDER', name: 'Render Token', sector: 'Crypto', basePrice: 7.4 },
  { ticker: 'INJ', name: 'Injective', sector: 'Crypto', basePrice: 22.5 },
  { ticker: 'SUI', name: 'Sui', sector: 'Crypto', basePrice: 0.85 },
  { ticker: 'PEPE', name: 'Pepe', sector: 'Crypto', basePrice: 1.2e-05 },
  { ticker: 'WIF', name: 'dogwifhat', sector: 'Crypto', basePrice: 2.1 },
  { ticker: 'SOFI', name: 'SoFi Technologies', sector: 'Finance', basePrice: 8.5 },
  { ticker: 'CLOV', name: 'Clover Health', sector: 'Healthcare', basePrice: 1.8 },
  { ticker: 'WISH', name: 'ContextLogic (Wish)', sector: 'Consumer', basePrice: 3.2 },
  { ticker: 'BB', name: 'BlackBerry Limited', sector: 'Technology', basePrice: 3.8 },
  { ticker: 'NOK', name: 'Nokia Corporation', sector: 'Technology', basePrice: 4.2 },
  { ticker: 'TLRY', name: 'Tilray Brands', sector: 'Healthcare', basePrice: 2.1 },
  { ticker: 'SNDL', name: 'SNDL Inc.', sector: 'Healthcare', basePrice: 1.55 },
  { ticker: 'WKHS', name: 'Workhorse Group', sector: 'Industrial', basePrice: 0.85 },
  { ticker: 'NKLA', name: 'Nikola Corporation', sector: 'Industrial', basePrice: 0.65 },
  { ticker: 'GOEV', name: 'Canoo Inc.', sector: 'Consumer', basePrice: 0.35 },
  { ticker: 'SPCE', name: 'Virgin Galactic', sector: 'Industrial', basePrice: 1.8 },
  { ticker: 'OPEN', name: 'Opendoor Technologies', sector: 'Real Estate', basePrice: 2.4 },
  { ticker: 'SKLZ', name: 'Skillz Inc.', sector: 'Technology', basePrice: 0.55 },
  { ticker: 'ASTS', name: 'AST SpaceMobile', sector: 'Communication', basePrice: 18.5 },
  { ticker: 'IONQ', name: 'IonQ, Inc.', sector: 'Technology', basePrice: 12.4 },
  { ticker: 'RKLB', name: 'Rocket Lab USA', sector: 'Industrial', basePrice: 6.5 },
  { ticker: 'JOBY', name: 'Joby Aviation', sector: 'Industrial', basePrice: 5.8 },
  { ticker: 'MVST', name: 'Microvast Holdings', sector: 'Industrial', basePrice: 1.2 },
  { ticker: 'QS', name: 'QuantumScape Corp.', sector: 'Technology', basePrice: 6.2 },
  { ticker: 'LAZR', name: 'Luminar Technologies', sector: 'Technology', basePrice: 3.5 },
  { ticker: 'LIDR', name: 'AEye Inc.', sector: 'Technology', basePrice: 0.8 },
  { ticker: 'DNA', name: 'Ginkgo Bioworks', sector: 'Healthcare', basePrice: 0.35 },
  { ticker: 'ME', name: '23andMe Holding', sector: 'Healthcare', basePrice: 0.25 },
  { ticker: 'BARK', name: 'BARK, Inc.', sector: 'Consumer', basePrice: 1.1 },
  { ticker: 'BYND', name: 'Beyond Meat', sector: 'Consumer', basePrice: 6.5 },
  { ticker: 'NNDM', name: 'Nano Dimension', sector: 'Technology', basePrice: 2.8 },
  { ticker: 'DM', name: 'Desktop Metal', sector: 'Technology', basePrice: 3.2 },
  { ticker: 'BFLY', name: 'Butterfly Network', sector: 'Healthcare', basePrice: 1.5 },
  { ticker: 'GENI', name: 'Genius Sports', sector: 'Technology', basePrice: 5.2 },
  { ticker: 'MAPS', name: 'WM Technology', sector: 'Technology', basePrice: 0.6 },
  { ticker: 'IRNT', name: 'IronNet Cybersecurity', sector: 'Technology', basePrice: 0.45 },
  { ticker: 'RDW', name: 'Redwire Corporation', sector: 'Industrial', basePrice: 8.5 },
  { ticker: 'BNGO', name: 'Bionano Genomics', sector: 'Healthcare', basePrice: 0.4 },
  { ticker: 'GEVO', name: 'Gevo, Inc.', sector: 'Energy', basePrice: 0.9 },
  { ticker: 'PLUG', name: 'Plug Power Inc.', sector: 'Energy', basePrice: 3.5 },
  { ticker: 'FCEL', name: 'FuelCell Energy', sector: 'Energy', basePrice: 1.2 },
  { ticker: 'BE', name: 'Bloom Energy', sector: 'Energy', basePrice: 12.5 },
  { ticker: 'RUN', name: 'Sunrun Inc.', sector: 'Energy', basePrice: 14.2 },
  { ticker: 'ARRY', name: 'Array Technologies', sector: 'Energy', basePrice: 12.8 },
  { ticker: 'CHPT', name: 'ChargePoint Holdings', sector: 'Energy', basePrice: 1.4 },
  { ticker: 'BLNK', name: 'Blink Charging', sector: 'Energy', basePrice: 2.5 },
  { ticker: 'STEM', name: 'Stem, Inc.', sector: 'Energy', basePrice: 0.8 },
  { ticker: 'MULN', name: 'Mullen Automotive', sector: 'Consumer', basePrice: 0.08 },
  { ticker: 'FFIE', name: 'Faraday Future', sector: 'Consumer', basePrice: 0.05 },
  { ticker: 'SIRI', name: 'Sirius XM Holdings', sector: 'Communication', basePrice: 2.8 },
  { ticker: 'TELL', name: 'Tellurian Inc.', sector: 'Energy', basePrice: 0.6 },
  { ticker: 'BIOR', name: 'Biora Therapeutics', sector: 'Healthcare', basePrice: 0.35 },
  { ticker: 'PRPH', name: 'ProPhase Labs', sector: 'Healthcare', basePrice: 1.5 },
  { ticker: 'HPNN', name: 'Hop-On Inc.', sector: 'Technology', basePrice: 0.003 },
  { ticker: 'ATER', name: 'Aterian Inc.', sector: 'Consumer', basePrice: 0.45 },
  { ticker: 'BBIG', name: 'Vinco Ventures', sector: 'Technology', basePrice: 0.15 },
  { ticker: 'CEI', name: 'Camber Energy', sector: 'Energy', basePrice: 0.08 },
  { ticker: 'PROG', name: 'Progenity Inc.', sector: 'Healthcare', basePrice: 0.2 },
  { ticker: 'TRVN', name: 'Trevena Inc.', sector: 'Healthcare', basePrice: 0.15 },
  { ticker: 'GSAT', name: 'Globalstar Inc.', sector: 'Communication', basePrice: 1.8 },
  { ticker: 'TTOO', name: 'T2 Biosystems', sector: 'Healthcare', basePrice: 0.1 },
  { ticker: 'SOUN', name: 'SoundHound AI', sector: 'Technology', basePrice: 5.5 },
  { ticker: 'BKKT', name: 'Bakkt Holdings', sector: 'Finance', basePrice: 1.2 },
  { ticker: 'AFRM', name: 'Affirm Holdings', sector: 'Finance', basePrice: 35.2 },
  { ticker: 'UPST', name: 'Upstart Holdings', sector: 'Finance', basePrice: 28.5 },
  { ticker: 'LMND', name: 'Lemonade Inc.', sector: 'Finance', basePrice: 15.2 },
  { ticker: 'PSFE', name: 'Paysafe Limited', sector: 'Finance', basePrice: 12.5 },
  { ticker: 'GME', name: 'GameStop Corp.', sector: 'Consumer', basePrice: 22.5 },
  { ticker: 'AMC', name: 'AMC Entertainment', sector: 'Consumer', basePrice: 4.2 },
  { ticker: 'BBBY', name: 'Bed Bath & Beyond', sector: 'Consumer', basePrice: 0.08 },
  { ticker: 'KOSS', name: 'Koss Corporation', sector: 'Consumer', basePrice: 4.8 },
  { ticker: 'EXPR', name: 'Express Inc.', sector: 'Consumer', basePrice: 1.2 },
  { ticker: 'NAKD', name: 'Centurion Corp.', sector: 'Consumer', basePrice: 0.3 },
  { ticker: 'CENN', name: 'Cenntro Electric', sector: 'Industrial', basePrice: 0.15 },
  { ticker: 'IVR', name: 'Invesco Mortgage', sector: 'Real Estate', basePrice: 8.5 },
  { ticker: 'DWAC', name: 'Digital World Acquisition', sector: 'Technology', basePrice: 18.5 },
  { ticker: 'PHUN', name: 'Phunware Inc.', sector: 'Technology', basePrice: 0.6 },
  { ticker: 'BGFV', name: 'Big 5 Sporting Goods', sector: 'Consumer', basePrice: 5.5 },
  { ticker: 'CATO', name: 'The Cato Corporation', sector: 'Consumer', basePrice: 7.2 },
  { ticker: 'DLTH', name: 'Duluth Trading', sector: 'Consumer', basePrice: 4.8 },
  { ticker: 'FLWS', name: '1-800-Flowers.com', sector: 'Consumer', basePrice: 6.8 },
  { ticker: 'CTRN', name: 'Citi Trends Inc.', sector: 'Consumer', basePrice: 20.5 },
  { ticker: 'PRTY', name: 'Party City', sector: 'Consumer', basePrice: 0.05 },
  { ticker: 'ZYNE', name: 'Zynerba Pharmaceuticals', sector: 'Healthcare', basePrice: 1.8 },
  { ticker: 'EDTX', name: 'EdtechX Holdings', sector: 'Technology', basePrice: 2.5 },
  { ticker: 'BNOX', name: 'Bionomics Ltd.', sector: 'Healthcare', basePrice: 3.2 },
  { ticker: 'HYMC', name: 'Hycroft Mining', sector: 'Materials', basePrice: 2.8 },
  { ticker: 'SOS', name: 'SOS Limited', sector: 'Technology', basePrice: 4.5 },
  { ticker: 'MDIA', name: 'MediaCo Holding', sector: 'Communication', basePrice: 0.8 },
  { ticker: 'AEHR', name: 'Aehr Test Systems', sector: 'Technology', basePrice: 14.5 },
  { ticker: 'SOXS', name: 'SemiConductor Bear ETF', sector: 'Technology', basePrice: 8.2 },
  { ticker: 'TQQQ', name: '3x NASDAQ Bull ETF', sector: 'Technology', basePrice: 55.5 },
  { ticker: 'UVXY', name: 'ProShares VIX Short-Term', sector: 'Finance', basePrice: 22.5 },
  { ticker: 'ENVX', name: 'Enovix Corporation', sector: 'Technology', basePrice: 8.5 },
  { ticker: 'CNTB', name: 'Connect Biopharma', sector: 'Healthcare', basePrice: 1.2 },
  { ticker: 'APRE', name: 'Aprea Therapeutics', sector: 'Healthcare', basePrice: 2.8 },
  { ticker: 'PSNY', name: 'Polestar Automotive', sector: 'Consumer', basePrice: 1.8 },
  { ticker: 'XPEV', name: 'XPeng Inc.', sector: 'Consumer', basePrice: 8.5 },
  { ticker: 'LI', name: 'Li Auto Inc.', sector: 'Consumer', basePrice: 28.5 },
  { ticker: 'VFS', name: 'VinFast Auto', sector: 'Consumer', basePrice: 4.2 },
  { ticker: 'RIDE', name: 'Lordstown Motors', sector: 'Consumer', basePrice: 0.1 },
  { ticker: 'FSR', name: 'Fisker Inc.', sector: 'Consumer', basePrice: 0.08 },
  { ticker: 'EVGO', name: 'EVgo Inc.', sector: 'Energy', basePrice: 2.5 },
  { ticker: 'SHIB', name: 'Shiba Inu', sector: 'Crypto', basePrice: 8.2e-06 },
  { ticker: 'BONK', name: 'Bonk', sector: 'Crypto', basePrice: 2.5e-05 },
  { ticker: 'FLOKI', name: 'Floki Inu', sector: 'Crypto', basePrice: 0.00015 },
  { ticker: 'MEME', name: 'Memecoin', sector: 'Crypto', basePrice: 0.018 },
  { ticker: 'ELON', name: 'Dogelon Mars', sector: 'Crypto', basePrice: 2e-07 },
  { ticker: 'BABYDOGE', name: 'Baby Doge Coin', sector: 'Crypto', basePrice: 2e-09 },
  { ticker: 'KISHU', name: 'Kishu Inu', sector: 'Crypto', basePrice: 8e-10 },
  { ticker: 'SAMO', name: 'Samoyedcoin', sector: 'Crypto', basePrice: 0.005 },
  { ticker: 'MYRO', name: 'Myro', sector: 'Crypto', basePrice: 0.08 },
  { ticker: 'POPCAT', name: 'Popcat', sector: 'Crypto', basePrice: 0.35 },
  { ticker: 'MEW', name: 'cat in a dogs world', sector: 'Crypto', basePrice: 0.003 },
  { ticker: 'BRETT', name: 'Brett', sector: 'Crypto', basePrice: 0.08 },
  { ticker: 'BOME', name: 'Book of Meme', sector: 'Crypto', basePrice: 0.008 },
  { ticker: 'SLERF', name: 'Slerf', sector: 'Crypto', basePrice: 0.15 },
  { ticker: 'TREMP', name: 'Doland Tremp', sector: 'Crypto', basePrice: 0.25 },
  { ticker: 'MOTHER', name: 'Mother Iggy', sector: 'Crypto', basePrice: 0.05 },
  { ticker: 'GME_COIN', name: 'GME (Solana)', sector: 'Crypto', basePrice: 0.002 },
  { ticker: 'TRUMP', name: 'MAGA', sector: 'Crypto', basePrice: 3.5 },
  { ticker: 'TURBO', name: 'Turbo', sector: 'Crypto', basePrice: 0.005 },
  { ticker: 'LADYS', name: 'Milady Meme Coin', sector: 'Crypto', basePrice: 1e-07 },
  { ticker: 'COQ', name: 'Coq Inu', sector: 'Crypto', basePrice: 3e-06 },
  { ticker: 'MOG', name: 'Mog Coin', sector: 'Crypto', basePrice: 1.5e-06 },
];
